### ISSUE TITLE
packaging

### ISSUE THREAD

**Issue by ghost** [larsks/python-netns#2]
Really cool idea! Any chance to get this packaged to make it available via pip3 or distro repos?

**Comment by larsks** [comment]
I dunno. Absent a good mechanism to automatically build new pypi packages from tagged releases on github, I'm not interested in the maintenance overhead (because I will invariably forget to update what's in pypi after fixing things here).  You can always install straight from github...

    pip install git+https://github.com/larsks/python-netns

**Comment by little-dude** [comment]
@larsks I'd really like to have this package on pypi, do you mind if I upload it under a different name?

Otherwise I'd be willing to contribute the CI boilerplate to upload new versions on pypi when you push a new tag.

**Comment by little-dude** [comment]
Since the package is GPLv3 I took the liberty to upload it on pypi, because it's much more convenient for me. Let me know if you want ownership of the package on pypi. Otherwise I'll watch this repo and update the package when there are updates. 

Also, thanks for this excellent wrapper.

**Comment by little-dude** [comment]
Btw if you really don't want `netns` to exist on pypi I'll use a different name. I didn't pick a different name because I didn't want it to look like I was stealing your work. Just let me know what you prefer.
