### ISSUE TITLE
Using Scapy with netns doesn't work

### ISSUE THREAD

**Issue by nabaco** [larsks/python-netns#4]
I'm trying to generate certain traffic from a network namespace using Scapy.
Using the standard example from their site to send ICMP packets, from within the netns, by entering the netns with "ip netns exec" works.

But trying to do the same using this module doesn't:
```
Traceback (most recent call last):
  File "./ping.py", line 16, in <module>
    p=sr1(IP(dst=sys.argv[1])/ICMP())
  File "/usr/local/lib/python3.8/dist-packages/scapy/sendrecv.py", line 648, in sr1
    s = conf.L3socket(promisc=promisc, filter=filter,
  File "/usr/local/lib/python3.8/dist-packages/scapy/arch/linux.py", line 501, in __init__
    set_promisc(self.ins, self.iface)
  File "/usr/local/lib/python3.8/dist-packages/scapy/arch/linux.py", line 181, in set_promisc
    mreq = struct.pack("IHH8s", get_if_index(iff), PACKET_MR_PROMISC, 0, b"")
  File "/usr/local/lib/python3.8/dist-packages/scapy/arch/linux.py", line 401, in get_if_index
    return int(struct.unpack("I", get_if(iff, SIOCGIFINDEX)[16:20])[0])
  File "/usr/local/lib/python3.8/dist-packages/scapy/arch/common.py", line 65, in get_if
    return ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
OSError: [Errno 19] No such device
```
I ran the script with sudo. Here is the script:
```py
#!/usr/bin/env python3
import netns
from scapy.all import sr1,IP,ICMP,send
import sys

with netns.NetNS(nsname="red"):
    p=sr1(IP(dst=sys.argv[1])/ICMP())
    if p:
        p.show()
```

I also tried this variation:
```py
#!/usr/bin/env python3
import netns
import os
from scapy.all import sr1,IP,ICMP,send
import sys

mypath = netns.get_ns_path(nspid=os.getpid())
targetpath = netns.get_ns_path(nsname="red")
if not targetpath:
    raise ValueError('invalid namespace')

myns = open(mypath)
with open(targetpath) as fd:
    netns.setns(fd, 0)

p=sr1(IP(dst=sys.argv[1])/ICMP())
if p:
    p.show()

netns.setns(myns, 0)
myns.close()                          
```

Notably, using this module with `subprocess.call(['ping', '192.168.0.1'])` works well.

I'm placing the issue here and not in Scapy project, since it seems that Scapy by itself works well inside the netns. The issue is switching netns's programmatically.

**Comment by larsks** [comment]
Could you provide me with information to reproduce the problem? In particular, how are you configuring the `red` namespace?

Looking at the traceback, if we place a `breakpoint()` just before this line:

```
  File "/usr/local/lib/python3.8/dist-packages/scapy/arch/linux.py", line 501, in __init__
    set_promisc(self.ins, self.iface)
```

We see that `self.iface` is `eth0`. If there is no `eth0` interface in the namespace, you're going to get the "No such device" error.

If you've configured another interface in your namespace, I *think* you can provide the interface name explicitly when you call `sr1`. From the docs:

```
scapy.all.sr1 = sr1(x, promisc=None, filter=None, iface=None, nofilter=0, *args, **kargs)
    Send packets at layer 3 and return only the first answer
```

I'll try this out myself this evening and see how things work out.

**Comment by larsks** [comment]
Additionally, it looks like some scapy variables are initialized probably when you import scapy, so even though your function call is running inside the appropriate network namespace, scapy "knows" about interfaces in the global namespace. Even when passing `iface="myinterface"`, when scapy tries to send a packet it determines the outbound interface in https://github.com/secdev/scapy/blob/master/scapy/arch/linux.py#L605, where it seems to refer to interfaces in the global namespace. Unless there's a way to force scapy to refresh it's view of the local network configuration, you may be out of luck.

For your simple example, this works, but seems sort of hacky:

```
#!/usr/bin/env python3
import netns
import sys

with netns.NetNS(nsname="red"):
    from scapy.all import sr1,IP,ICMP,send
    p=sr1(IP(dst=sys.argv[1])/ICMP(), iface='inside')
    if p:
        p.show()
```

Because we're importing `scapy` after changing the network namespace, it doesn't have the chance to cache information about the global namespace.

**Comment by nabaco** [comment]
Thanks @larsks, your hack indeed works. I'm closing the ticket, and will open a follow up on Scapy project.
